### ISSUE TITLE
Koshin - Missing Text

### ISSUE THREAD

**Issue by thecrazyscotsman** [Homusubi/Rising-Sun-II#3]
We are currently missing the following text:

LOC_CIVINFO_KOSHIN_SIZE
LOC_CIVINFO_KOSHIN_POPULATION
LOC_CITIZEN_KOSHIN_MALE (10)
LOC_CITIZEN_KOSHIN_FEMALE (10)
LOC_CITIZEN_KOSHIN_MODERN_MALE (10)
LOC_CITIZEN_KOSHIN_MODERN_FEMALE (10)

**Comment by Homusubi** [comment]
Done!
